version: "3"
services:
  db:
    image: mongo:latest
    ports:
      - "27017"
  redis-server:
    image: redis:latest
    ports:
      - "6379"
  app:
    build: .
    links:
      - db
      - redis-server
    ports:
      - "8080"
